version: "3.9"

services:
  darmisolutions-app:
    container_name: darmisolutions-prod
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    restart: unless-stopped
